### ISSUE TITLE
Unable to install in Laravel 7 application

### ISSUE THREAD

**Issue by FrankPeters** [okta/okta-sdk-php#84]
I am trying to install the Okta PHP SDK in a Laravel 7 application but I'm running into a version conflict with `tightenco/collect`. 

This is the error:

```
Using version ^1.2 for okta/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - okta/sdk 1.2.0 requires tightenco/collect 5.8.31 -> satisfiable by tightenco/collect[v5.8.31].
    - Installation request for okta/sdk ^1.2 -> satisfiable by okta/sdk[1.2.0].
    - Conclusion: remove symfony/var-dumper v5.0.7
    - Conclusion: don't install symfony/var-dumper v5.0.7
    - tightenco/collect v5.8.31 requires symfony/var-dumper >=3.4 <5
```

I see that the latest version of `tightenco/collect` is set to accept:
```
"symfony/var-dumper": "^3.4 || ^4.0 || ^5.0"
```

Is it possible to upgrade this dependency to a later version (~7)?

**Comment by LarryBarker** [comment]
@FrankPeters I have had the worst time using this package with Laravel applications. I originally had issues installing into a L5.5 application, and managed to finagle a work around. Unfortunately, it is time to upgrade to L6 as L5.5 is aproaching EOL this August.

I was afraid there would be issues with `tightenco/collect` as it caused the majority of issues for me before. Seeing your issue here has just confirmed my fears. 

Were you able to resolve the issue? I am no composer expert, but I am wondering if it is possible to simply require the version of `tightenco/collect` that is compatible with the version of Laravel being used? Tighten keeps the package in sync with Laravel releases, so you would think it would be possible to say "Hey, if we are using Laravel 6, install the most compatible version of `tightenco/collect`." or whatever. 

Okta's lack of support for Laravel is very frustrating. You would think they would have 1st party support for such a popular framework.

**Comment by malpertuis** [comment]
@LarryBarker 
Hi, we solved it currently by adding tightenco/collect in the composer.json as follows:
`"tightenco/collect": "7.9.2 as 5.8.31"`

This is by no means a proper fix, but its a good enough workaround till the time that Okta update there composer.json

**Comment by LarryBarker** [comment]
Which composer.json did you add this to? Your projects or you modified the
packages?

**Comment by malpertuis** [comment]
To our projects composer.json

**Comment by bretterer** [comment]
Hello!  I understand this is a rather old issue, but we are releasing a new version of the SDK that will include PHP8 support. This update also includes the switch to laravel/collection, which should solve this.  Please let us know if this doesn't help.

**Comment by FrankPeters** [comment]
Thanks! I will close this issue then in anticipation of the new release.
